// <auto-generated />
namespace GymLedger.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class v_12_PreviousLoginAndPasswords : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v_12_PreviousLoginAndPasswords));
        
        string IMigrationMetadata.Id
        {
            get { return "202503251425521_v_1.2_PreviousLoginAndPasswords"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
